-- Table for Sunny's Paintings
create table images (
    images_id serial primary key,
    category text,
    year decimal,
    title text,
    dimensions text,
    medium text, 
    orientation text,
    sold boolean,
    img text
);

-- Home Images
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Black Sand', '44in x 68in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/black-sand.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Mammoth', '42in x 38in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/mammoth.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Flight', '11in x 14in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/flight.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Manta', '16in x 20in', 'Oil on Canvas mounted on panel', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/manta.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Kinetic', '14in x 11in', 'Oil on Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/kinetic.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Might', '11in x 14in', 'Oil on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/might.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Radiate', '32in x 48in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/radiate.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Nebula', '12in x 16in', 'Oil on Canvas mounted on panel', 'horizontal', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/nebula.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Chase', '16in x 12in', 'Oil on Canvas mounted on panel', 'vertical', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/chase.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Harvest', '11in x 14in', 'Oil on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/harvest.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('home', 2017, 'Expedition', '16in x 12in', 'Oil on Canvas mounted on panel', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/home/expedition.jpg');


                                                                                -- PAINTINGS SECTION --
-- Paintings 2006
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2006', 2006, 'The Final Round', '54in x 40in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2006/paintings2006-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2006', 2006, 'It''s Not Enough', '43in x 34in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2006/paintings2006-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2006', 2006, 'The Only One', '38in x 50in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2006/paintings2006-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2006', 2006, 'Make it Tomorrow', '50in x 40in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2006/paintings2006-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2006', 2006, 'Go Ahead', '5in x 40in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2006/paintings2006-05.jpg');

-- Paintings 2008
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Float', '46in x 70in', 'Oil on Canvas', 'horizontal', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Left Behing', '42in x 32in', 'Oil on Canvas', 'vertical', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Fallen', '20in x 46in', 'Oil on Canvas', 'horizontal', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Take You Out', '20in x 46in', 'Oil on Canvas', 'horizontal', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Aftershock', '20in x 46in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Burn Out Bright', '20in x 46in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Runway', '20in x 46in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Untitled', '20in x 46in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2008', 2008, 'Blur', '16ft across', 'Acrylic paint, pastel, graphite, vellum and canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2008/paintings2008-09.jpg');

-- Paintings 2010
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2010', 2010, 'Rise', '50in x 74in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2010/paintings2010-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2010', 2010, 'Regrets', '62in x 82in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2010/paintings2010-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2010', 2010, 'River', '50in x 74in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2010/paintings2010-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2010', 2010, 'Below', '62in x 82in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2010/paintings2010-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2010', 2010, 'Sliver', '44in x 72in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2010/paintings2010-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2010', 2010, 'Steel', '20in x 46in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2010/paintings2010-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2010', 2010, 'Flourescent', '20in x 46in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2010/paintings2010-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2010', 2010, 'Flourescent Detailed View', '', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2010/paintings2010-08.jpg');

-- Paintings 2012
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'A Breath', '44in x 70in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'Aurora', '44in x 68in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'Night Fog', '44in x 68in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'Escalate', '49in x 22in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'The Underground', '44in x 70in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'Passing', '24in x 48in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-06-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'Heads Up', '44in x 68in', 'Oil on Canvas', 'horizontal', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-07-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'Overturn', '68in x 44in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'Sirens', '32in x 42in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-09.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2012', 2012, 'Veil', '42in x 32in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2012/paintings2012-10.jpg');

-- Paintings 2014
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2014', 2014, 'Curl', '30in x 48in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2014/paintings2014-01-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2014', 2014, 'Split', '44in x 68in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2014/paintings2014-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2014', 2014, 'Molten', '46in x 30in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2014/paintings2014-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2014', 2014, 'The Fall', '42in x 30in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2014/paintings2014-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2014', 2014, 'Within Reach', '32in x 42in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2014/paintings2014-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2014', 2014, 'Pacific', '48in x 30in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2014/paintings2014-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2014', 2014, 'Negative Seven', '30in x 44in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2014/paintings2014-07-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2014', 2014, 'Negative Seven Detailed View', '', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2014/paintings2014-08.jpg');

-- Paintings 2015
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Untitled', '', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Untitled', '', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Untitled', '', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Tickle', '48in x 32in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Sneak', '44in x 68in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Accumulation', '30in x 44in', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-06-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Accumulation Detailed View', '', 'Oil on Canvas', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Spotlight', '14in x 11in', 'Oil on Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('paintings2015', 2015, 'Carved', '48in x 24in', 'Oil on Canvas', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/paintings/2015/paintings2015-09.jpg');

                                                                            -- WORKS ON PAPER SECTION --
-- Works on Paper 2006
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2006', 2006, 'Road of Resistance', '40in x 30in', 'Charcoal on Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2006/works2006-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2006', 2006, 'Do You See Me', '40in x 30in', 'Charcoal on Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2006/works2006-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2006', 2006, 'Cross the Dark Line', '24in x 34in', 'Charcoal on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2006/works2006-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2006', 2006, 'Run', '30in x 20in', 'Charcoal on Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2006/works2006-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2006', 2006, 'Seeing it Through the Rough', '43in x 34in', 'Charcoal on Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2006/works2006-05.jpg');

-- Works on Paper 2009
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Take Off', '33in x 66in', 'Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-01-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Break #2', '42in x 36in', 'Conte on Mylar', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Break #1', '42in x 36in', 'Conte on Mylar', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'The Peak', '8in x 6in', 'Etching', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Spin', '6in x 4.5in', 'Etching', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Shrapnel', '4in x 6in', 'Etching', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Barrier', '10in x 8in', 'Pastel on Paper', 'vertical', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Lit', '8in x 10in', 'Pastel on Paper', 'horizontal', true, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Signal', '10in x 8in', 'Pastel on Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-09.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Atlantic', '8in x 10in', 'Pastel on Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-10.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Unearth #1', '24in x 36in', 'Conte on Vellum', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-11.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Unearth #1', '24in x 36in', 'Conte on Vellum', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-12.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Untitled', '', 'Wall Installation: Mixed Media on Collaged Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-13.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Raging', '36in x 52in', 'Pastel and Acrylic on Collaged Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-14.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Addition Subtraction', '38in x 50in', 'Pastel and Acrylic on Collaged Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-15.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2009', 2009, 'Fragments of Memories', '50in x 38in', 'Pastel and Acrylic on Collaged Paper', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2009/works2009-16.jpg');

-- Works on Paper 2012
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Untitled', '48in x 72in', 'Conte and Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Untitled', '48in x 78in', 'Conte and Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-02-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Backwards', '8in x 10in', 'Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Glide', '8in x 10in', 'Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Sted', '8in x 10in', 'Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Lowland', '8in x 10in', 'Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Mobile', '8in x 10in', 'Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Nite Light', '8in x 10in', 'Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Willow', '8in x 10in', 'Pastel on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-09.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Passing', '18in x 24in', 'Charcoal on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-10.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'By Force', '18in x 24in', 'Charcoal on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-11.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'DC Subway', '18in x 24in', 'Charcoal on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-12.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2012', 2012, 'Ravine', '18in x 24in', 'Charcoal on Paper', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2012/works2012-13.jpg');

-- Works on Paper 2016
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'vertical', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('works2016', 2016, 'Untitled', '', '', 'horizontal', false, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/works/2016/works2016-09.jpg');


                                                                            -- Installation Section --

-- Installation Images
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-01-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-04-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-09.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-10.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-11.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-12.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-13.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-14.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-15.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-16.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-17.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-18.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-19.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-20.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-21.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-22.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-23.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-24.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-25.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-26.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-27.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-28.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-29.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-30.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-31.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-32.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-33.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-34.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-35.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-36.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-37.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-38.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-39.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('installation', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/installation/installation-40.jpg');


                                                                                -- Student Works Section --

-- Student Works
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-04.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-05.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-09.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-10.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-11.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-12.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-13.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-14.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-15.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-16.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-17.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-18.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-19.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-20.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-21-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-22-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-23.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-24.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-25.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-26.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-27.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-28.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-29.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-30.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-31.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-32.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-33.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('studentwork', null, null, null, null, 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/studentwork/studentwork-34.jpg');


                                                                    -- Commissioned Section --

-- Commissioned
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Botanical Gardens', null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-01.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Botanical Gardens', null, null, 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-02.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Botanical Gardens Plein Air Competition', '12in x 12in', 'Oil on Canvas', 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-03.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Botainica Show 2014', '18in x 48in', 'Oil on Canvas', 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-04-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Botainica Show 2014', '18in x 48in', 'Oil on Canvas', 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-05-mobile.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'LVA''s Art Squared 2014' , '8in x 8in', 'Oil on Canvas', 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-06.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'LVA''s Art Squared 2014' , '8in x 8in', 'Oil on Canvas', 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-07.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Golden Gate', '42in x 34in', 'Oil on Canvas', 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-08.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Golden Gate Detailed View', null, 'Oil on Canvas', 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-09.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Golden Gate Detailed View', null, 'Oil on Canvas', 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-10.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Drawing for Golden Gate Painting', '24in x 26in', 'Charcoal on Paper', 'vertical', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-11.jpg');
insert into images (category, year, title, dimensions, medium, orientation, sold, img) values ('commissioned', null, 'Drawing for Golden Gate Painting', '24in x 26in', 'Charcoal on Paper', 'horizontal', null, 'https://s3.amazonaws.com/content.danlubbers.com/sunny-content/images/commissioned/commissioned-12.jpg');
